"""empty message

Revision ID: 312d8f66c5d3
Revises: 794ff2cccee
Create Date: 2014-10-03 15:09:41.259000

"""

# revision identifiers, used by Alembic.
revision = '312d8f66c5d3'
down_revision = '794ff2cccee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pin', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin')
    ### end Alembic commands ###
