"""empty message

Revision ID: 533808e0503f
Revises: None
Create Date: 2014-09-24 17:26:24.041000

"""

# revision identifiers, used by Alembic.
revision = '533808e0503f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_tokens', sa.Column('hashed_password', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_tokens', 'hashed_password')
    ### end Alembic commands ###
