"""empty message

Revision ID: 794ff2cccee
Revises: None
Create Date: 2014-09-24 21:19:22.598000

"""

# revision identifiers, used by Alembic.
revision = '794ff2cccee'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_tokens', sa.Column('hashed_password', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_tokens', 'hashed_password')
    ### end Alembic commands ###
